name: cards-app-backend-dev

services:
  psql_db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cards_app_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - psql_db
    # Static environment variables
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: psql_db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE_NAME: cards_app_backend
      FILE_SYSTEM_STORAGE_DIRECTORY: /data/images/
      GCP_PROJECT_ID: cards-app-dev
      FIREBASE_AUTH_EMULATOR_HOST: gcp_emulator:9099  # Does not include the http:// prefix
    # Dynamic environment variables
    env_file:
      - .env
    # Override CMD to enable hot-reload with --reload flag
    # prettier-ignore
    command: ["uv", "run", "uvicorn", "src.cards_app_backend.core.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      # Mount image files volume (shared with postgres for now)
      - image_files:/data/images/
      # Mount source code for hot-reloading during development
      - ./src/cards_app_backend:/app/src/cards_app_backend
      # Mock data for in memory repository
      - ./data/:/app/data/

  gcp_emulator:
    build:
      context: ./gcp_emulators
      args:
        - PROJECT_ID=cards-app-dev
    restart: unless-stopped
    ports:
      - "4000:4000" # Emulator UI
      - "9099:9099" # Auth
    volumes:
      - gcp_emulator_data:/data/emulator_data

volumes:
  postgres_data:
  image_files:
  gcp_emulator_data:
